### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by jmarcher** [mirimmad/zeta-lang#6]
As a suggestion, I would love to help with the core. But in some parts, it is really hard to understand what you were trying to do.

I think it would help a lot if you comment your code. Even for you after a few months, it will turn difficult to guess what some parts are for.

**Comment by mirimmad** [comment]
I'll look into this.

**Comment by mirimmad** [comment]
There is a problem with opening files. Zeta doesn't show 'file not found' to the user. Maybe you can fix that.

**Comment by mirimmad** [comment]
Fixed
